### ISSUE TITLE
Add jolokia CORS workaround to quickstarts

### ISSUE THREAD

**Issue by davsclaus** [fabric8io/quickstarts#431]
so they work until openshift have their stuff fixed
https://github.com/openshift/origin/issues/2619

@rhuss has this snipped code we need
https://gist.github.com/rhuss/ccee4f12ff131d430824

**Comment by davsclaus** [comment]
10:24:46]  <ro14nd>	 The problem is a kubernetes/openshift issue --> https://github.com/openshift/origin/issues/2619
[10:25:07]  <ro14nd>	 Until this is fixed we have only this workaround

**Comment by davsclaus** [comment]
You need to create a file "jolokia-access.xml" in src/main/resources

**Comment by davsclaus** [comment]
@rhuss any thoughs on this workaround for the jolokia WAR agent, eg for our quickstarts that is WAR files such as
https://github.com/fabric8io/quickstarts/blob/master/quickstarts/war/camel-servlet/src/main/webapp/WEB-INF/web.xml

Is there a config value we can set in web.xml etc?

**Comment by davsclaus** [comment]
Ah found it in the ref doc
https://jolokia.org/reference/html/security.html#d0e2558

**Comment by rhuss** [comment]
Yes, should be same: When you put it into the `src/main/resources` of the war project it should work, too.

Please note that the workaround should be removed as soon as kubernetes is fixed (although it shouldnt harm if still there since the api proxy will add the required CORS headers on its own anyway)

**Comment by davsclaus** [comment]
See also
https://github.com/fabric8io/fabric8/issues/4038
